HexCode.EquipmentManager.Hub/Models/ErrorViewModel.cs
using System;

namespace HexCode.EquipmentManager.Hub.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HexCode.EquipmentManager.Hub/Models/Shared/TableStateViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HexCode.EquipmentManager.Data;
using HexCode.EquipmentManager.Data.Infrastructure;

namespace HexCode.EquipmentManager.Hub.Models.Shared
{
    public class TableStateViewModel
    {
        public string SortedColumn { get; set; }
        public SortDirection SortedDirection { get; set; }
        public int PageNumber { get; set; }
        public int PageSize { get; set; }
        public string FilterText { get; set; }

        public PagingInfo PagingInfo
        {
            get
            {
                return new PagingInfo(this.PageSize, this.PageNumber);
            }
        }

        protected void PopulateFilteringInfo(FilteringInfo filteringInfo)
        {
            filteringInfo.FilterText = this.FilterText;
            filteringInfo.SortedProperty = this.SortedColumn;
            filteringInfo.SortedDirection = this.SortedDirection;
        }
    }
}

HexCode.EquipmentManager.Hub/Models/UserManagement/CreateMapper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HexCode.EquipmentManager.Core.Models;
using HexCode.EquipmentManager.Hub.Infrastructure;

namespace HexCode.EquipmentManager.Hub.Models.UserManagement
{
    public class CreateMapper : BaseViewToDomainMapper<CreateViewModel, User>
    {
        public override void MapToDomainModel(CreateViewModel viewModel, User domainModel)
        {
            domainModel.FirstName = viewModel.FirstName;
            domainModel.LastName = viewModel.LastName;
        }

        protected override User CreateDomainModel()
        {
            return new User();
        }
    }
}

HexCode.EquipmentManager.Hub/Models/UserManagement/CreateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using LocalResources = HexCode.EquipmentManager.Hub.Resources.UserManagement.Create;

namespace HexCode.EquipmentManager.Hub.Models.UserManagement
{
    public class CreateViewModel
    {
        [Display(ResourceType = typeof(LocalResources), Name = "FirstNameLabel")]
        [Required(ErrorMessageResourceType = typeof(LocalResources), ErrorMessageResourceName = "FirstNameEmptyError")]
        public string FirstName { get; set; }

        [Display(ResourceType = typeof(LocalResources), Name = "LastNameLabel")]
        [Required(ErrorMessageResourceType = typeof(LocalResources), ErrorMessageResourceName = "LastNameEmptyError")]
        public string LastName { get; set; }

        [Display(ResourceType = typeof(LocalResources), Name = "EmailLabel")]
        [Required(ErrorMessageResourceType = typeof(LocalResources), ErrorMessageResourceName = "EmailEmptyError")]
        [EmailAddress(ErrorMessageResourceType = typeof(LocalResources), ErrorMessageResourceName = "EmailFormatError")]
        public string Email { get; set; }
    }
}

HexCode.EquipmentManager.Hub/Models/UserManagement/ListItemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HexCode.EquipmentManager.Hub.Models.UserManagement
{
    public class ListItemViewModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Id { get; set; }
    }
}

HexCode.EquipmentManager.Hub/Models/UserManagement/UserTableStateViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HexCode.EquipmentManager.Data.SearchCriteria;
using HexCode.EquipmentManager.Hub.Models.Shared;

namespace HexCode.EquipmentManager.Hub.Models.UserManagement
{
    public class UserTableStateViewModel : TableStateViewModel
    {
        public UserFilteringInfo.UserStateFilter StateFilter { get; set; }

        public UserFilteringInfo FilteringInfo
        {
            get
            {
                UserFilteringInfo filteringInfo = new UserFilteringInfo()
                {
                    UserState = this.StateFilter
                };

                base.PopulateFilteringInfo(filteringInfo);

                return filteringInfo;
            }
        }
    }
}

HexCode.EquipmentManager.Hub/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using HexCode.EquipmentManager.Hub.Models;
using Microsoft.AspNetCore.Mvc;

namespace HexCode.EquipmentManager.Hub.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HexCode.EquipmentManager.Hub/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HexCode.EquipmentManager.Core.Models;
using HexCode.EquipmentManager.Data;
using HexCode.EquipmentManager.Data.Infrastructure;
using HexCode.EquipmentManager.Data.Services;
using HexCode.EquipmentManager.Hub.Infrastructure;
using HexCode.EquipmentManager.Hub.Models.UserManagement;
using HexCode.EquipmentManager.Hub.Models.Shared;
using Microsoft.AspNetCore.Mvc;

namespace HexCode.EquipmentManager.Hub.Controllers
{
    public class UserManagementController : Controller
    {
        private readonly IUserService _userService;

        public UserManagementController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return PartialView("CreateDialog");
        }

        [HttpPost]
        public IActionResult Create(CreateViewModel viewModel)
        {
            IActionResult toReturn;

            if (this.ModelState.IsValid == true)
            {
                CreateMapper mapper = new CreateMapper();
                User domainModel = mapper.MapToDomainModel(viewModel);

                Result result = _userService.Create(domainModel);

                toReturn = new AjaxResult(result);
            }
            else
            {
                toReturn = new AjaxResult(this.ModelState);
            }

            return toReturn;
        }

        [HttpPost]
        public IActionResult UserList(UserTableStateViewModel tableState)
        {
            PagedList<User> result =_userService.List(tableState.PagingInfo, tableState.FilteringInfo);

            return Json(new {pageCount = result.PageCount, pageSize = tableState.PageSize, pageNumber = result.PageNumber, totalItems = result.ItemCount, items = result.Items});
        }
    }
}

HexCode.EquipmentManager.Hub/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

HexCode.EquipmentManager.Hub/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HexCode.EquipmentManager.Hub/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="ui grid">
    <div class="four wide column">
        <div class="ui segment">
        </div>
    </div>
</div>

HexCode.EquipmentManager.Hub/Views/Shared/_Layout.cshtml
@using LocalResources = HexCode.EquipmentManager.Hub.Resources.Shared.Layout

@{
    Html.AddStyle("/css/semantic.css");
    Html.AddStyle("/css/hub.less");
    Html.AddStyle("/css/materialdesignicons.css");

    Html.AddDebugScript("/js/Shared/less.js");
    Html.AddScript("/js/Shared/jquery.js");
    Html.AddScript("/js/Shared/utilities.js");
    Html.AddScript("/js/Shared/dialog-utilities.js");
    Html.AddScript("/js/Shared/semantic.js");
    Html.AddScript("/js/Shared/knockout.js");
    Html.AddScript("/js/Shared/knockout-unobtrusive.js");
    Html.AddScript("/js/Shared/vbridge.js");
    Html.AddScript("/js/Shared/vbridge-semantic.js");
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    @Html.RenderStyles()
</head>
<body class="menu wrapper">
    <div id="side-menu" class="ui vertical left visible sidebar accordion menu">
        <a class="logo item" href="@Url.Action("Index", "Home")">
            <img class="ui centered image" src="images/placeholder.png" />
        </a>
        <a class="item" href="@Url.Action("Index", "Home")">
            <i class="mdi mdi-gauge"></i>
            @LocalResources.DashboardMenuItem
        </a>
        <div class="item">
            <a class="active title">
                <i class="dropdown icon"></i>
                @LocalResources.ManageMenuItem
            </a>
            <div class="content">
                <a class="item" href="@Url.Action("Index", "UserManagement")">
                    <i class="mdi mdi-account-group"></i>
                    @LocalResources.UsersMenuItem
                </a>
                <a class="item">
                    @LocalResources.ModelsMenuItem
                </a>
                <a class="item">
                    @LocalResources.InventoryMenuItem
                </a>
            </div>
        </div>
    </div>

    <div class="ui main body">
        <div id="top-menu" class="ui borderless inner menu">
            <a class="menu toggler item" href="#">
                <i class="icon mdi mdi-menu"></i>
            </a>
            <div class="item header">@ViewData["Title"]</div>

            <div class="right menu">
                <div class="ui dropdown item">
                    <img class="ui mini circular image" src="/images/placeholder.png">
                    <div class="menu">
                        <div class="header">User McUserface</div>
                        <div class="divider"></div>
                        <a class="item">
                            @LocalResources.SettingsMenuItem
                        </a>
                        <a class="item">
                            @LocalResources.HelpMenuItem
                        </a>
                        <div class="divider"></div>
                        <a class="item">
                            @LocalResources.LogoutMenuItem
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="ui inner body">
            @RenderBody()
        </div>

        <div class="ui inner footer">
            <small>Footer Stuff Here</small>
        </div>
    </div>

    @Html.RenderScripts()

    <script>
        $(function () {
            //Hilight the current menu item and expand any accordions
            var currentMenuItem = $("#side-menu a.item[href='" + location.pathname + "']:not(.logo)");
            currentMenuItem.addClass("active");
            currentMenuItem.closest(".content").addClass("active");

            $(".ui.accordion").accordion();
            $(".ui.dropdown").dropdown();

            $(".menu.toggler").on("click", function () {
                $(this).closest(".menu.wrapper").toggleClass("toggled");
            });
        });

        //Make modals autobind ko properties
        ko.addAutomaticBindingEvent(events.dialog.loaded);
        vbridge.semantic.register({ validationEvents: events.dialog.loaded });
    </script>
</body>
</html>

HexCode.EquipmentManager.Hub/Views/UserManagement/CreateDialog.cshtml
@using HexCode.EquipmentManager.Hub.Models.UserManagement

@model CreateViewModel

<div class="ui modal" data-bind-inputs="true" data-model="CreateViewModel">
    <div class="header">Create User</div>
    <div class="content">
        <form class="ui form error" data-bind="formValidation: isValid">
            <div class="ui error message" data-bind="visible: validationErrors().length > 0">
                <ul data-bind="foreach: validationErrors">
                    <li data-bind="text: $data"></li>
                </ul>
            </div>

            <div class="two fields">
                <div class="field">
                    @Html.LabelFor(m => m.FirstName)
                    @Html.EditorFor(m => m.FirstName)
                </div>

                <div class="field">
                    @Html.LabelFor(m => m.LastName)
                    @Html.EditorFor(m => m.LastName)
                </div>
            </div>
            
            <div class="field">
                @Html.LabelFor(m => m.Email)
                @Html.EditorFor(m => m.Email)
            </div>
        </form>
    </div>
    <div class="actions">
        <div class="ui basic positive button" data-bind="submitDialog: { url: '@Url.Action("Create")', messages: validationErrors }, enabled: isValid">Create</div>
        <div class="ui basic negative cancel button">Cancel</div>
    </div>
</div>

@* TODO [Andrew]: Need to decide if we want these in separate files or inline like this *@
<script>
    function CreateViewModel() {
        var _this = this;
        this.isValid = ko.observable(false);
        this.validationErrors = ko.observableArray();
        this.succesCallback = function() {
            //TODO [Andrew]: Notify that a new user has been added
            alert("New user created!");
        }
    }
</script>

HexCode.EquipmentManager.Hub/Views/UserManagement/Index.cshtml
@{
    ViewData["Title"] = "User Management";

    Html.AddScript("/js/Shared/utilities.js");
    Html.AddScript("/js/Shared/knockout-utilityBindings.js");
    Html.AddScript("/js/Shared/knockout-tableBindings.js");
    Html.AddScript("/js/UserManagement/Index.js");
}

<div id="user-list" data-model="IndexViewModel" data-arg-list-url="@Url.Action("UserList")" data-arg-create-url="@Url.Action("Create")" data-bind="loading: isLoading">
    <div id="user-list-header" class="ui top attached separatorless menu">
        <div class="header item">Users</div>
        <a href="#" class="item" data-bind="click: createUser">
            <i class="mdi mdi-account-plus"></i>
        </a>

        <div class="right menu">
            <div class="ui transparent input">
                <input class="prompt" type="text" placeholder="Search">
            </div>
            <a href="#" class="item">
                <i class="icon mdi mdi-magnify"></i>
            </a>
            <a href="#" class="item">
                <i class="mdi mdi-refresh"></i>
            </a>
            <div class="ui dropdown item">
                <i class="mdi mdi-settings"></i>
                <div class="menu">
                    <div class="header">Page Size</div>
                    <div class="item">5</div>
                    <div class="item active">10</div>
                    <div class="item">25</div>
                    <div class="item">50</div>
                    <div class="item">All</div>
                </div>
            </div>
        </div>
    </div>

    <table id="user-list-table" class="ui attached celled striped table">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Active</th>
                <th>@* Actions *@</th>
            </tr>
        </thead>
        <tbody data-bind="foreach: users">
            <tr>
                <td data-bind="text: firstName"></td>
                <td data-bind="text: lastName"></td>
                <td>Email</td>
                <td class="collapsing center aligned">
                    <i class="mdi icon" data-bind="css: {'mdi-check green': isActive, 'mdi-close red': !isActive}"></i>
                </td>
                <td class="collapsing">
                    <button class="ui basic primary icon button"><i class="icon mdi mdi-pencil"></i></button>
                    <div class="ui icon top left pointing dropdown basic primary button">
                        <i class="icon mdi mdi-settings"></i>
                        <div class="menu">
                            <div class="header">Options</div>
                            <a href="#" class="item">
                                <i class="red icon mdi mdi-close"></i>
                                Delete
                            </a>
                            <a href="#" class="item">
                                <i class="icon mdi mdi-account-off"></i>
                                Deactivate
                            </a>
                        </div>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>

    <div id="user-list-footer" class="ui bottom attached separatorless menu">
        <div class="item">
            Page &nbsp; <span data-bind="text: pageNumber"></span>/<span data-bind="text: pageCount"></span>
        </div>
        <div class="right pagination menu">
            <a class="item" data-bind="css: {disabled: isFirstPage}, click: goToFirst">
                <i class="mdi mdi-chevron-double-left"></i>
            </a>
            <a class="item" data-bind="css: {disabled: isFirstPage}, click: goToPrevious">
                <i class="mdi mdi-chevron-left"></i>
            </a>

            <!-- ko foreach: pages-->
            <a class="item" data-bind="click: $parent.goToPage, text: $data, css: {active: $parent.pageNumber() == $data}"></a>
            <!-- /ko -->

            <a class="item" data-bind="css: {disabled: isLastPage}, click: goToNext">
                <i class="mdi mdi-chevron-right"></i>
            </a>
            <a class="item" data-bind="css: {disabled: isLastPage}, click: goToLast">
                <i class="mdi mdi-chevron-double-right"></i>
            </a>
        </div>
    </div>
</div>